### PR TITLE
Enhance the Create Application Template

### LINKED ISSUE #56: Extend the example skeleton to include App container concept
**Enhancement**

The example should be extended to demonstrate the recommended structure for building an application (to date) and not just a widget.

This would include adding a container `App.ts` and also adding some functionality using `Themeable`, properties passing and an example event handler.

### PR DESCRIPTION
**Pull request by agubler**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Enhance the skeleton application template, using the demo example from @dylans' demo.

Resolves #56

### CODE REVIEW

**Review by rorticus — APPROVED** [review]

**Comment by rishson** [comment]
Should we be adding the `stranger` example, or rename it to something a bit more generic?
Also, should we add code comments?

**Comment by agubler** [comment]
@rishson I think a bit of fun is okay, lots of people will understand the theme :) 

Re code comments, do you think there is anything in there that needs it? I.e. if I was starting an application would I want to keep them?

**Comment by rishson** [comment]
I think we might want comments that what has been created in `HelloWorld.ts` is not a bare bones widget - but already has an event handler and a custom property.
I would've expanded the classes mutation in `render` so its not so shortcutty, and added a '//if stranger is true then add the 'upsidedown' class from our imported css' type comment.

**Comment by agubler** [comment]
@rishson what do you mean "shortcutty", I would have thought it was the point to demonstrate the power of things like `this.classes` (also I don't think a ternary is that "shortcutty")? I had assumed that consumers would be able to see that the `HelloWorld.ts` widget has custom properties and an event handler.

Perhaps the comments can be followed up in a subsequent pull requests if you raise an issue detailing what you feel is required here.

**Comment by rishson** [comment]
Will raise an issue about adding more comments (either in code or a synced tutorial).

**Review by rishson — APPROVED** [review]

**Pull request merged**
