### PR TITLE
Move to next tag for @dojo deps

### PR DESCRIPTION
**Pull request by agubler**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Related to the proposed [process change](https://github.com/dojo/meta/issues/183) for managing pre-release `beta` and `rc` release sets

Related to https://github.com/dojo/meta/issues/183

### CODE REVIEW

**Review by rishson — COMMENTED** [review]
Why is `cli` on `beta1` rather than `next`?

**Review by dylans — APPROVED** [review]

**Review by dylans — DISMISSED** [review]
Actually take that back, is beta1 intentional or did you mean next for cli?

**Comment by agubler** [comment]
@dylan it's intentional and as a result of having circular deps 😫 

but this is a dev dependency and `cli`'s dependency on `create-app` is not so I think that this is better way of doing the dependencies until we resolve that.

**Comment by agubler** [comment]
@rishson please see comment to @dylans above

**Review by rishson — APPROVED** [review]

**Pull request merged**
